drop table if exists tb_video CASCADE;

create table tb_video(
    video_id bigint generated by default as identity,
    title varchar(255) NOT NULL,
    descricao varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    primary key(video_id)
);



insert into tb_video values(1,'Curso de Java - Iniciando','Curso de java para iniciantes','http://testewa.com.br')