drop table if exists tb_video CASCADE;
drop table if exists tb_categoria CASCADE;
drop table if exists tb_profile CASCADE;
drop table if exists tb_user CASCADE;
drop table if exists tb_user_profile CASCADE;

create table tb_video(
    video_id bigint generated by default as identity,
    title varchar(255) NOT NULL,
    descricao varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    categoria_id bigint NOT NULL ,
    primary key(video_id)
);

create table tb_categoria(
    categoria_id bigint generated by default as identity,
    title varchar(255) NOT NULL,
    color varchar(255) NOT NULL,
    primary key(categoria_id)
);

create table tb_profile(
    profile_id bigint generated by default as identity,
    name_profile varchar(255) NOT NULL,
    primary key(profile_id)
);

create table tb_user(
    user_id bigint generated by default as identity,
    username varchar(255) NOT NULL,
    password_user varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    primary key(user_id)
);


create table tb_user_profile(
     user_id bigint NOT NULL,
     profile_id bigint NOT NULL
);

alter table tb_user_profile add constraint uk_tb_user_profile_profile_id unique(profile_id);

alter table tb_user_profile add constraint fk_tb_user_profile_profile_id unique(profile_id);

alter table tb_user_profile add constraint fk_tb_user_profile_user_id foreign key (user_id) references tb_user;

alter table tb_video add foreign key(categoria_id) references tb_categoria(categoria_id);

insert into tb_categoria values(1,'LIVRE','White');

insert into tb_video values(1,'curso de Testes de Integração: Testes de SQL e DAOs automatizados em Java','Desenvolvedores e desenvolvedoras Java com base em testes de unidade, que querem ampliar os seus conhecimentos em cenários que exigem integração.','https://www.alura.com.br/curso-online-teste-integracao-sql-daos-automatizados-java',1);

insert into tb_profile values(1,'ADMIN');

insert into tb_profile values(2,'USER');

insert into tb_user values(1,'admin','$2y$12$aNK.FURoeGsUS6EfGaVr.OPNR1R46EDlFiYAfwQsvDc8p7rrQrUHe','admin@email.com');

insert into tb_user_profile values(1,1);